name: "Terraform CI Deployment"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  terraform:

    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
         version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'


      # - name: "Gcloud login"
      #   uses: 'google-github-actions/auth@v1'
      #   with:
      #     credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

      # - name: Terraform Format
      #   run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -out workspace.plan -lock=false
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run:  terraform apply -auto-approve -lock=false
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
