name: "Terraform CI Deployment"
on:
  push:
    branches:
      - main
  pull_request:
  # workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        # with:
        #   reposetory: 'https://github.com/'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: cd terraform && terraform init
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

      - name: Terraform Format
        run: cd terraform &&  terraform fmt -check

      - name: Terraform Plan
        run: cd terraform &&  terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: cd terraform &&  terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
