name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:
      name: Setup Gcloud Account
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: code/frontend
      env:
        IMAGE_NAME: ${{secrets.region}}-docker.pkg.dev/${{ secrets.project_id }}/${{ secrets.basename}}/fe
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
          with:
            version: '>= 363.0.0'

        - name: 'Use gcloud CLI'
          run: 'gcloud info'
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet



        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Test Docker image
          run: docker run $IMAGE_NAME sh -c "go test -v"

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.project_id }} --image $IMAGE_NAME --region us-central1 --platform managed