name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

    deploy_frontend:
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        defaults:
          run:
           working-directory: code/frontend
        env:
          IMAGE_NAME: ${{secrets.region}}-docker.pkg.dev/${{ secrets.project_id }}/${{ secrets.basename}}/fe
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Test Docker image
          run: docker run $IMAGE_NAME sh -c "go test -v"

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.project_id }} --image $IMAGE_NAME --region us-central1 --platform managed